# Generated by Django 5.2.7 on 2025-11-17 12:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
