# Generated by Django 5.2.7 on 2025-12-04 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_alter_product_sale_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpricelevel',
            name='minimal_quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='productpricelevel',
            constraint=models.CheckConstraint(condition=models.Q(('minimal_quantity__gte', 1)), name='price_level_minimal_quantity_positive'),
        ),
    ]
