# Generated by Django 5.2.7 on 2025-11-18 17:04

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erp', '0006_alter_document_doc_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Середньодобовий продаж (ADS)')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Останнє оновлення')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_data', to='erp.product', verbose_name='Продукт')),
            ],
        ),
        migrations.CreateModel(
            name='ReplenishmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('status', models.CharField(choices=[('DRAFT', 'Чернетка (розрахунок)'), ('ORDER_CREATED', 'Замовлення сформовано')], default='DRAFT', max_length=20, verbose_name='Статус')),
                ('global_coverage_days', models.PositiveIntegerField(default=14, verbose_name='Цільове покриття (днів)')),
                ('global_credit_terms', models.PositiveIntegerField(default=45, verbose_name='Кредитні умови (днів)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.warehouse', verbose_name='Склад поповнення')),
            ],
        ),
        migrations.CreateModel(
            name='ReplenishmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=128, verbose_name='Бренд')),
                ('product_sku', models.CharField(max_length=64, verbose_name='SKU Продукту')),
                ('product_name', models.CharField(max_length=256, verbose_name='Назва Продукту')),
                ('inventory', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Запаси на складі')),
                ('average_daily_sales', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Середньодобовий продаж (ADS)')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна продажу')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Закупівельна ціна')),
                ('pricelevel_minimum_quantity', models.PositiveIntegerField(default=1, verbose_name='Мін. кількість для ціни')),
                ('system_coverage_days', models.PositiveIntegerField(default=0, verbose_name='Цільове покриття (днів)')),
                ('credit_terms', models.PositiveIntegerField(default=0, verbose_name='Кредитні умови (днів)')),
                ('system_suggested_quantity', models.PositiveIntegerField(default=0, verbose_name='Система пропонує замовити')),
                ('best_quantity', models.PositiveIntegerField(default=0, verbose_name='Оптимальна кількість для замовлення')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.product', verbose_name='Продукт (ID)')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.warehouse', verbose_name='Склад')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='replenishment.replenishmentreport', verbose_name='Звіт')),
            ],
            options={
                'verbose_name': 'Рядок поповнення',
                'verbose_name_plural': 'Рядки поповнення',
                'unique_together': {('report', 'product', 'warehouse')},
            },
        ),
    ]
