# Generated by Django 5.2.7 on 2025-11-20 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('replenishment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replenishmentitem',
            options={'ordering': ['product__brand__name', 'product__sku'], 'verbose_name': 'Рядок поповнення', 'verbose_name_plural': 'Рядки поповнення'},
        ),
    ]
