# Generated by Django 5.2.7 on 2025-11-20 19:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replenishment', '0002_alter_replenishmentitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='replenishmentreport',
            name='max_budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15),
        ),
        migrations.AddField(
            model_name='replenishmentreport',
            name='max_investment_period',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='replenishmentreport',
            name='min_budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15),
        ),
    ]
