# Generated by Django 5.2.7 on 2025-11-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replenishment', '0003_replenishmentreport_max_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='replenishmentreport',
            name='deals_variants_json',
            field=models.JSONField(default=dict),
        ),
    ]
