# Generated by Django 5.2.7 on 2025-11-20 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('replenishment', '0004_replenishmentreport_deals_variants_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replenishmentreport',
            name='deals_variants_json',
        ),
    ]
