# Generated by Django 5.2.7 on 2025-11-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replenishment', '0005_remove_replenishmentreport_deals_variants_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='replenishmentreport',
            name='deals_variants_json',
            field=models.BinaryField(blank=True, null=True, verbose_name='Дані алгоритму (Pickle)'),
        ),
    ]
