# Generated by Django 5.2.7 on 2025-11-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Чернетка'), ('POSTED', 'Проведено'), ('CANCELED', 'Скасовано')], default='DRAFT', max_length=16),
        ),
    ]
